import "bootstrap/dist/css/bootstrap.min.css";
import Bootstrap from "./components/Bootstrap";

export const metadata = {
  title: "Generator QR",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
      <Bootstrap />
    </html>
  );
}
